### PR TITLE
Upgrade to Java 8 (Issue #76)

### PR DESCRIPTION
**Pull request by patrikvarga**
Fix for issue #76 as https://github.com/mpatric/mp3agic/issues/76

### CODE REVIEW

**Comment by TheDiamondYT1** [comment]
Squash commits?

**Comment by TheDiamondYT1** [comment]
Build fails aswell

**Comment by patrikvarga** [comment]
> Build fails aswell

That's due to Travis CI config:
```
"jdk": "oraclejdk7",
```

From Maven log:
```
Java version: 1.7.0_80, vendor: Oracle Corporation
```

**Comment by patrikvarga** [comment]
Squashed.

**Comment by hennr** [comment]
I updated the travis build to java 8 (as you could have done, too). If you rebase master the build should succeed and I will the PR.

**Comment by hennr** [comment]
Well, I built and merged locally. Thanks for the PR.

**Pull request merged**
