### PR TITLE
fix for issue 120

### PR DESCRIPTION
**Pull request by tmzkt**
- Added changelog.md
- Preferred id3v2 over id3v1 for `getGenre()` and `getGenreDescription()`
- No changes made to `Mp3File` since I don't think there would be any noticeable behavior changes that would come from switching the order the tags are initialized

### CODE REVIEW

**Comment by hennr** [comment]
Perfect, thanks @tmzkt

**Comment by hennr** [comment]
Hey @tmzkt , I spoke with @mpatric about giving you commit rights for mp3agic.
We are looking for more contributors and you seem to be a good fit :)

Are you interested?

**Comment by tmzkt** [comment]
Hi @hennr @mpatric that would be awesome! It will make simple commits much easier. Of course, for things that I am unsure about, I will still need input from you two.

**Comment by hennr** [comment]
Great, can you add @tmzkt then @mpatric ?

**Comment by mpatric** [comment]
Yep, done

**Comment by hennr** [comment]
Welcome aboard @tmzkt !

**Comment by tmzkt** [comment]
Thanks guys! I look forward to working with you.

**Pull request merged**
